name: Deploy to EC2
on:
  push:
    branches:
      - main  # Change this to your deployment branch if different
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host:  ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e
          cd /home/ubuntu  # or your preferred directory
          if [ ! -d "Cloud-Websites" ]; then
            git clone https://github.com/Ydeem/Cloud-Websites.git
          else
            cd Cloud-Websites
            git pull origin main
          fi
